//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trackingentradaGrupoHumano.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class loginuser
    {
        public int id { get; set; }
        [DisplayName("Código Empleado")]
      
        [Required]
        public Nullable<int> codigoempleado { get; set; }
        [Required]
        [StringLength(50,MinimumLength =3)]
        [DisplayName("Nombre del empleado")]
        public string nombre { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 3)]
        [DisplayName("Apellido del empleado")]
        public string apellido { get; set; }
        [Required]
        [StringLength(75, MinimumLength = 3)]
        [DisplayName("Correo electrónico")]
        public string email { get; set; }
        [Required]
        [StringLength(75, MinimumLength = 3)]
        [DisplayName("Contraseña")]
        public string contrasena { get; set; }
    }
}
