//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trackingentradaGrupoHumano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBENTRADA
    {
        public int IDENTRADA { get; set; }
        public Nullable<int> IDDEPART { get; set; }
        public Nullable<int> IDOCUPACION { get; set; }
        public Nullable<int> IDMOTIVOENTRADA { get; set; }
        public string CEDULA { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<System.DateTime> FECHAENTRADA { get; set; }
        public string TiempoESTIMADO { get; set; }
        public Nullable<int> TENIACITA { get; set; }
        public Nullable<int> Entro { get; set; }
        public Nullable<int> Localidad { get; set; }
        public Nullable<int> vpresidencial { get; set; }
        public Nullable<int> PISO { get; set; }
        public Nullable<int> COORDENADA { get; set; }
        public Nullable<int> codigoempleado { get; set; }
        public string NombreAnfitrion { get; set; }
        public string HORAENTRADA { get; set; }
        public string HORASALIDA { get; set; }
        public Nullable<int> EstadoSolicitud { get; set; }
    
        public virtual CONFIGURACION CONFIGURACION { get; set; }
        public virtual CONFIGURACION CONFIGURACION1 { get; set; }
        public virtual CONFIGURACION CONFIGURACION2 { get; set; }
        public virtual TBDEPARTAMENTO TBDEPARTAMENTO { get; set; }
        public virtual TBMOTIVOENTRADA TBMOTIVOENTRADA { get; set; }
        public virtual TBOCUPACION TBOCUPACION { get; set; }
        public virtual tblocalidad tblocalidad { get; set; }
        public virtual CONFIGURACION CONFIGURACION3 { get; set; }
        public virtual TBCOORDENADA TBCOORDENADA { get; set; }
        public virtual TBPISO TBPISO { get; set; }
        public virtual estado estado { get; set; }
    }
}
